PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX spin:    <http://spinrdf.org/spin#>

CONSTRUCT {
  [] a spin:ConstraintViolation ;
    spin:violationRoot ?s ;
    spin:violationPath ?p ;
    spin:invalidValue ?date ;
    rdfs:label "Empty literal value"@en , 
      "Prázdná textová hodnota"@cs
    .
}
WHERE {
  GRAPH ?validatedGraph {
    ?s ?p ?literal .
    FILTER (isLiteral(?literal) && (str(?literal) = "")) 
  }
}
